# Generated by Django 3.1.5 on 2022-04-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Translator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language_code',
            name='Letters_Ain',
            field=models.CharField(max_length=2, null=1),
        ),
        migrations.AlterField(
            model_name='language_code',
            name='Letters_Alef',
            field=models.CharField(max_length=2, null=1),
        ),
        migrations.AlterField(
            model_name='language_code',
            name='Letters_Be',
            field=models.CharField(max_length=2, null=1),
        ),
        migrations.AlterField(
            model_name='language_code',
            name='Letters_Che',
            field=models.CharField(max_length=2, null=1),
        ),
        migrations.AlterField(
            model_name='language_code',
            name='Letters_Dal',
            field=models.CharField(max_length=2, null=1),
        ),
        migrations.AlterField(
            model_name='language_code',
            name='Letters_Fe',
            field=models.CharField(max_length=2, null=1),
        ),
        migrations.AlterField(
            model_name='language_code',
            name='Letters_Ghaf',
            field=models.CharField(max_length=2, null=1),
        ),
        migrations.AlterField(
            model_name='language_code',
            name='Letters_Ghain',
            field=models.CharField(max_length=2, null=1),
        ),
        migrations.AlterField(
            model_name='language_code',
            name='Letters_He',
            field=models.CharField(max_length=2, null=1),
        ),
        migrations.AlterField(
            model_name='language_code',
            name='Letters_Hyphen',
            field=models.CharField(max_length=2, null=1),
        ),
        migrations.AlterField(
            model_name='language_code',
            name='Letters_Jim',
            field=models.CharField(max_length=2, null=1),
        ),
        migrations.AlterField(
            model_name='language_code',
            name='Letters_Kaf',
            field=models.CharField(max_length=2, null=1),
        ),
        migrations.AlterField(
            model_name='language_code',
            name='Letters_Khe',
            field=models.CharField(max_length=2, null=1),
        ),
        migrations.AlterField(
            model_name='language_code',
            name='Letters_Lam',
            field=models.CharField(max_length=2, null=1),
        ),
        migrations.AlterField(
            model_name='language_code',
            name='Letters_MiM',
            field=models.CharField(max_length=2, null=1),
        ),
        migrations.AlterField(
            model_name='language_code',
            name='Letters_Noon',
            field=models.CharField(max_length=2, null=1),
        ),
        migrations.AlterField(
            model_name='language_code',
            name='Letters_Pe',
            field=models.CharField(max_length=2, null=1),
        ),
        migrations.AlterField(
            model_name='language_code',
            name='Letters_Re',
            field=models.CharField(max_length=2, null=1),
        ),
        migrations.AlterField(
            model_name='language_code',
            name='Letters_Sad',
            field=models.CharField(max_length=2, null=1),
        ),
        migrations.AlterField(
            model_name='language_code',
            name='Letters_Se',
            field=models.CharField(max_length=2, null=1),
        ),
        migrations.AlterField(
            model_name='language_code',
            name='Letters_Shin',
            field=models.CharField(max_length=2, null=1),
        ),
        migrations.AlterField(
            model_name='language_code',
            name='Letters_Sin',
            field=models.CharField(max_length=2, null=1),
        ),
        migrations.AlterField(
            model_name='language_code',
            name='Letters_Ta',
            field=models.CharField(max_length=2, null=1),
        ),
        migrations.AlterField(
            model_name='language_code',
            name='Letters_Te',
            field=models.CharField(max_length=2, null=1),
        ),
        migrations.AlterField(
            model_name='language_code',
            name='Letters_Vav',
            field=models.CharField(max_length=2, null=1),
        ),
        migrations.AlterField(
            model_name='language_code',
            name='Letters_Ye',
            field=models.CharField(max_length=2, null=1),
        ),
        migrations.AlterField(
            model_name='language_code',
            name='Letters_Za',
            field=models.CharField(max_length=2, null=1),
        ),
        migrations.AlterField(
            model_name='language_code',
            name='Letters_Zad',
            field=models.CharField(max_length=2, null=1),
        ),
        migrations.AlterField(
            model_name='language_code',
            name='Letters_Zal',
            field=models.CharField(max_length=2, null=1),
        ),
        migrations.AlterField(
            model_name='language_code',
            name='Letters_Ze',
            field=models.CharField(max_length=2, null=1),
        ),
        migrations.AlterField(
            model_name='language_code',
            name='Letters_Zhe',
            field=models.CharField(max_length=2, null=1),
        ),
    ]
