# Generated by Django 3.1.5 on 2022-04-26 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Translator', '0002_auto_20220423_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language_code',
            name='Number',
        ),
    ]
