# Generated by Django 3.1.5 on 2022-04-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Translator', '0003_remove_language_code_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language_code',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
