# Generated by Django 3.1.5 on 2022-04-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Translator', '0004_auto_20220426_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='language_code',
            name='M',
            field=models.CharField(max_length=2, null=1),
            preserve_default=1,
        ),
    ]
