# Generated by Django 3.1.5 on 2022-04-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Translator', '0005_language_code_m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language_code',
            name='M',
        ),
        migrations.AddField(
            model_name='language_code',
            name='Letters_HeJimi',
            field=models.CharField(max_length=2, null=1),
            preserve_default=1,
        ),
        migrations.AddField(
            model_name='language_code',
            name='Letters_Qaf',
            field=models.CharField(max_length=2, null=1),
            preserve_default=1,
        ),
    ]
