# Generated by Django 3.1.5 on 2022-05-05 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Translator', '0007_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.CharField(max_length=10000, null=1)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Translator.users')),
            ],
        ),
    ]
